version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rullafy-data-api
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8086:8085"
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:16.1
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
